### PR TITLE
adapted to master changes

### PR DESCRIPTION
**Pull request by flying-sheep**
dunno if there’s better options than `.collect::<Vec<T>>().into_boxed_slice()`

### CODE REVIEW

**Comment by flying-sheep** [comment]
needs [this](https://github.com/BurntSushi/quickcheck/pull/50) to build

**Comment by japaric** [comment]
Changes look good to me, let's wait until quickcheck is working again, before merging this.

**Comment by flying-sheep** [comment]
just test with flying-sheep/quickcheck@prelude-changes :)

**Comment by flying-sheep** [comment]
ok to test now!

**Comment by flying-sheep** [comment]
huh? did you change complex.rs or were there yet more master changes?

**Comment by japaric** [comment]
More [assoc types stuff landed](https://github.com/rust-lang/rust/pull/20490). I think it already got in the nightlies.

**Comment by flying-sheep** [comment]
yeah, ~~damn~~. i’ll update then fix it.

i really shouldn’t be frustrated that’s what i get for not waiting a few months until rust is stable ;)

**Comment by flying-sheep** [comment]
ok, once japaric/complex.rs#9 is merged, i’ll update this project’s use of Add/Mul/…

**Comment by flying-sheep** [comment]
or you could merge this and i’ll do another PR with the other changes?

**Comment by japaric** [comment]
@flying-sheep either way is fine, I'll let you pick ;-)

**Comment by flying-sheep** [comment]
well, if you don’t squash commits, the history will be pretty after merging all at once, so why not do it like that!

**Comment by flying-sheep** [comment]
wait. `check_line_lengths.sh` makes the build fail? i’m calling bullshit ;)

**Comment by japaric** [comment]
:100:

**Comment by flying-sheep** [comment]
woo!

**Pull request merged**
